apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: apirule
  namespace: asif-test
spec:
  gateway: asif-test/asif-test-gateway
  host: a0896a9db16b143c9966c6a847ccbc36-1181281374.eu-central-1.elb.amazonaws.com
  rules:
    - path: /startboot1/test
      methods: ["GET"]
      accessStrategies:
        - handler: jwt
          config:
            jwks_urls:
            -  https://ais-dev-support-rwgc9yp1.accounts.ondemand.com/oauth2/certs
    - path: /workverse/test
      methods: ["GET"]
      accessStrategies:
        - handler: noop

