apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: logpipeline1i
spec:
  input:
    application:
      containers: {}
      namespaces: {}
  output:
    http:
      dedot: false
      host: 
      value: http://127.0.0.1:3100
      uri: /loki/api/v1/push  
