apiVersion: telemetry.kyma-project.io/v1alpha1
kind: TracePipeline
metadata:
  name: jaeger-pipeline
  namespace: asif-test1  
spec:
  output:
    otlp:
      endpoint:
        value: http://telemetry-trace-collector-internal.kyma-system.svc.cluster.local:4317

