apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: workverse-apirule
  namespace: asif-test
spec:
  gateway: asif-test/asif-test-gateway
  host: a0896a9db16b143c9966c6a847ccbc36-1181281374.eu-central-1.elb.amazonaws.com
  rules:
  - accessStrategies:
    - handler: noop
    methods:
    - GET
    path: /test
  service:
    name: workverse-fn-svc
    namespace: asif-test
    port: 8000        

